### ISSUE TITLE
[Bug] Unexpected Mouse-click behaviors

### ISSUE THREAD

**Issue by dggriffin** [hsingh23/deckjam#1]
- Right-clicking selects a row
- Middle-clicking selects a row
- Holding any mouse button and scrolling inverts the selection of any row it passes over
   - This is a problem because scrolling by holding the middle-mouse button selects everything the cursor passes over.

**Comment by hsingh23** [comment]
Ah yes, that's the intended effect

**Comment by dggriffin** [comment]
Ah -- I see. Any way to ensure that you're dealing with the left-click only? (Or at least filter out middle click?)

**Comment by hsingh23** [comment]
The idea is to select cards like you would select times on this website -> http://whenisgood.net/

I've added checkboxes recently and I'm working on making it so you can only click checkboxes on mobile. I should have that up shortly. Let me know what you think

**Comment by hsingh23** [comment]
Fixed by removing drag to select . It doesn't make sense with cards.
