### ISSUE TITLE
[UX Suggestion] Card visualization

### ISSUE THREAD

**Issue by dggriffin** [hsingh23/deckjam#3]
Rather than dumping the data in rows, consider visualizing the flashcards as two "cards".

**Comment by hsingh23** [comment]
Interesting, rows seems compact. I'll try cards and see how it goes

**Comment by dggriffin** [comment]
You can always media query back to minimalistic rows if screen size plays poorly with a card format.


Taking inspiration from Quizlet, consider adding more references to the original source of the data (creator of the deck, number of cards/terms, etc)
![image](https://cloud.githubusercontent.com/assets/774648/21153000/a953adfc-c136-11e6-85a2-50d6ce2db7c9.png)

**Comment by hsingh23** [comment]
The more I think about it, the more I like the idea of these cards within cards.
The problem with tables is varied content length of tds wastes space and looks bad.
![image](https://cloud.githubusercontent.com/assets/1136514/21171075/89187520-c197-11e6-84eb-050d8f6ba0ed.png)

**Comment by hsingh23** [comment]
I like the way google photos select works in mobile. The desktop experience is not so nice. I think I'll make it a goal to get there

**Comment by hsingh23** [comment]
![image](https://cloud.githubusercontent.com/assets/1136514/21290781/ae2df5e6-c495-11e6-9258-ad39b6dda3fb.png)
![image](https://cloud.githubusercontent.com/assets/1136514/21290960/4b2f46e6-c49c-11e6-8058-646a7b90e566.png)

**Comment by hsingh23** [comment]
I've implemented something substantial - now time to ab test
